config/routes.rb
Rails.application.routes.draw do
  
  root 'site_pages#listings'
  get '/home', to: 'site_pages#home'
  get '/profile', to: 'site_pages#profile'
  get '/listings', to: 'site_pages#listings'
  get '/notifications', to: 'site_pages#notifications'
  get '/contact', to: 'site_pages#contact'
  get '/admin', to: 'site_pages#admin'
  post '/admin', to: 'site_pages#changeActivity'
  
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  
  post '/listings', to: 'site_pages#movePrivate'
  post '/home', to: 'site_pages#movePublic'
  
  get '/newlisting', to: 'shifts#new'
  post '/newlisting', to: 'shifts#create'
  
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  resources :users
  resources :shifts
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/preference.rb
class Preference < ApplicationRecord
end

app/models/qualification.rb
class Qualification < ApplicationRecord
end

app/models/shift.rb
class Shift < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  validates :firstname,  presence: true, length: { maximum: 50 }
  validates :lastname,  presence: true, length: { maximum: 50 }
  validates :password, presence: true, length: { maximum: 50 }
  validates :phonenumber, presence: true, length: { maximum: 10 }
  
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :emailaddress, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  
  def create
    user = User.find_by(emailaddress: params[:session][:emailaddress])
    if user
      if user.isactive == true
        log_in user
        redirect_to home_path
      else
        flash.now[:danger] = 'Inactive account, contact system admin'
        redirect_to login_path
      end
    else
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end
  
  def destroy
    log_out
    redirect_to root_url
  end
end

app/controllers/shifts_controller.rb
class ShiftsController < ApplicationController
    def new
    end
    
    def create
      @theUser = User.find(session[:user_id])
      starttime = params[:starttime]
      endtime = params[:endtime]
      shiftlength = params[:shiftlength]
      department = params[:department]
    
      if starttime != nil && endtime != nil && shiftlength != nil && department != nil
        shift = Shift.new
        shift.starttime = starttime
        shift.endtime = endtime
        shift.shiftlength = shiftlength
        shift.storeid = @theUser.storeid
        shift.ispublic = true
        shift.department = department
        shift.save

        redirect_to listings_path
      else
        render "new"
      end
    end
end

app/controllers/site_pages_controller.rb
class SitePagesController < ApplicationController
  def home
    @shifts = Shift.all
    @theUser = User.find(session[:user_id])
    render 'home'
  end

  def profile
    @theUser = User.find(session[:user_id])
  end

  def listings
    if logged_in?
      @preferences = Preference.find_by(userid: session[:user_id])
      @shiftScore = 0
      @theUser = User.find(session[:user_id])
    end
    @shifts = Shift.all
    render 'listings'
  end
  
  def movePrivate
    if logged_in?
      @preferences = Preference.find_by(userid: session[:user_id])
      @shiftScore = 0
      @theUser = User.find(session[:user_id])
    end
    @shifts = Shift.all
    @shift = Shift.find(params[:id])
    @shift.update(ispublic: "false")
    @shift.update(userid: session[:user_id])
    render 'listings'
  end
  
  def movePublic
    @theUser = User.find(session[:user_id])
    @shifts = Shift.all
    @shift = Shift.find(params[:id])
    @shift.update(ispublic: "true")
    render 'home'
  end
  
  def sortList
  #Going to fetch the user's id
  #Going to check the preferences table based on the user id
  #Going to score the list items based on preference
    @theList = Shift.all
    @preferences = Preference.find_by(userid: session[:user_id])
  
  end
  
  def notifications
    
  end
  
  def contact
  
  end
  
  def admin
    @users = User.all
    if logged_in?
      @theUser = User.find(session[:user_id])
    end
  end
  
  def changeActivity
    @users = User.all
    @user = User.find(params[:id])
    if @user.isactive == false
      @user.update(isactive: "true")
    else
      @user.update(isactive: "false")
    end
    render 'admin'
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def new
    end
    
    def create
      firstname = params[:firstname]
      lastname = params[:lastname]
      password = params[:password]
      phonenumber = params[:phonenumber]
      emailaddress = params[:emailaddress]
    
      user = User.new
      user.firstname = firstname
      user.lastname = lastname
      user.password = password
      user.phonenumber = phonenumber
      user.emailaddress = emailaddress
      user.storeid = storeid
      user.isactive = true
      user.ismanager = false
      user.isadmin = false
      
      if user.valid?
        user.save 
        session[:user_id] = user.id
        redirect_to root_url, notice: "Logged in!"
      else
        @errors = user.errors.full_messages
        render "new"
      end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  #Log in a user
  def log_in(user)
    session[:user_id] = user.id
  end
  
  # Returns the current logged-in user (if any).
  def current_user
    if session[:user_id]
      @current_user ||= User.find_by(id: session[:user_id])
    end
  end
  
  # Returns true if the user is logged in, false otherwise.
  def logged_in?
    !current_user.nil?
  end  
  
  def log_out
  session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/site_pages_helper.rb
module SitePagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <title>Junctions</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="css/layout.css" type="text/css">
    <!--[if lt IE 9]><script src="scripts/html5shiv.js"></script><![endif]-->
  </head>

  <body>
    
    
    <div class="wrapper row1">
  <header id="header" class="clear">
    <div id="hgroup">
      <h1><a href="#">Junctions.</a></h1>
    </div>
  </header>
    </div>
    
    
    
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/shifts/new.html.erb
<!DOCTYPE html>
<html lang="en" dir="ltr">
<head>
<title>Profile</title>
<meta charset="UTF-8">
<link rel="stylesheet" href="css/layout.css" type="text/css">
<!--[if lt IE 9]><script src="scripts/html5shiv.js"></script><![endif]-->
</head>
<body>
<div class="wrapper row1">
  <header id="header" class="clear">
    <nav>
      <ul>
        <% if logged_in? %>
        <li class="last"><a><%= link_to "Log out", logout_path, method: :delete %></li>
        <% else %>
        <li><%= link_to "Log in", login_path %></li>
              <p>Not logged in</p>
        <% end %>
      </ul>
    </nav>
  </header>
</div>
<div class="wrapper row2">
  <div id="container" class="clear">

    <!-- content body -->
    <section id="shout">
      
      <h3><a><%= link_to "return to main page",   home_path %></a></h3>

    </section>
    <!-- main content -->
    <section id="services" class="clear">

      <!-- article 3 -->
      <h1>Create a shift: </h1>
      <article class="three_third center lastbox">
<div class="row justify-content-md-center mt-5">
<p>Note: In the department entry, 1 is Cashier, 2 is Stock Handler, 3 is Dairy, 4 is Deli, 5 is Bakery</p>
    <div class="col-4">
        <%= form_tag newlisting_path do |form| %>
        <div class="form-group">
            <% if @errors != nil %>
            <div class="alert alert-danger" role="alert">
                <% @errors.each do |error| %>
                <div><%= error %></div>
                <% end %>
            </div>
            <% end %>
        </div>
        <div class="form-group">
            <label><%= label_tag :starttime %></label>
            <%= text_field_tag :starttime, "", class: 'form-control' %>
            <small id="startHelp" class="form-text text-muted">Shift Start time</small>
        </div>
        <div class="form-group">
            <label><%= label_tag :endtime %></label>
            <%= text_field_tag :endtime, "", class: 'form-control' %>
            <small id="endHelp" class="form-text text-muted">Shift End time</small>
        </div>
        <div class="form-group">
            <label><%= label_tag :shiftlength %></label>
            <%= text_field_tag :shiftlength, "", class: 'form-control' %>
            <small id="shiftHelp" class="form-text text-muted">Shift length (end - start)</small>
        </div>
        <div class="form-group">
            <label><%= label_tag :department %></label>
            <select name="department" id="department" class="form-control">
                <option>1</option>
                <option>2</option>
                <option>3</option>
                <option>4</option>
                <option>5</option>
            </select>
            <small id="departmentHelp" class="form-text text-muted">Select department</small>
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
        <% end %>
    </div>
</div>

<script>
    function getDepartments(storeId){
        axios({
            method: 'GET', 
            url: "/departments?store=" + storeId,
            headers: {
                'X-CSRF-Token': document.querySelector("meta[name=csrf-token]").content
            }
        })
        .then(function(response) {
            if(response && response.data){
                const departments = response.data;
                const storeDDL = document.querySelector("#department");
                storeDDL.innerHTML = '';
                departments.forEach((dep)=>{
                    let dept = document.createElement('option');
                    dept.value = dep.id;
                    dept.innerHTML = dep.name;

                    storeDDL.appendChild(dept);
                });
            }
        })
        .catch(function(error) {
            console.log(error);
        });
    }
</script>
      </article>

    </section>
    <!-- ########################################################################################## -->
    <!-- ########################################################################################## -->
    <!-- ########################################################################################## -->
    <!-- ########################################################################################## -->
    <!-- / content body -->
  </div>
</div>
<!-- footer -->

</body>
</html>

app/views/site_pages/admin.html.erb
<% if logged_in? %>
  <% if @theUser.isadmin == true %>
    <table>
        <tr>
            <th>User ID</th>
            <th>First Name</th>
            <th>Last Name</th>
            <th>Phone Number</th>
            <th>Email Address</th>
            <th>Store ID</th>
            <th>Manager Status</th>
            <th>Active Status</th>
        </tr>
        <% @users.each do |user| %>
          <tr>
            <td><%= user.id %></td>
            <td><%= user.firstname %></td>
            <td><%= user.lastname %></td>
            <td><%= user.phonenumber %></td>
            <td><%= user.emailaddress %></td>
            <td><%= user.storeid %></td>
            <td><%= user.ismanager %></td>
            <td><%= user.isactive %> <%= link_to "Change", {:controller => "site_pages",
                                           :action => "changeActivity",
                                           :id => user.id,
                                           :isactive => user.isactive}, method: "post",
                                        class: "btn btn-sm btn-success" %></td>
          </tr>
        <% end %>
    </table>
  <% else %>
    <p>Nice try mate, come back when you're an admin.</p>
  <% end %>
<% else %>    
  <p>You're not even a user, let alone an admin.</p>
<% end %>

app/views/site_pages/home.html.erb
<!DOCTYPE html>

<html lang="en" dir="ltr">
<head>
<title>Employee Main</title>
<meta charset="UTF-8">
<link rel="stylesheet" href="css/layout.css" type="text/css">
<!--[if lt IE 9]><script src="scripts/html5shiv.js"></script><![endif]-->
</head>
<body>
<div class="wrapper row1">
  <header id="header" class="clear">
    <nav>
      <ul>
        <li class="last"><a><%= link_to "Log out", logout_path, method: :delete %></li>
      </ul>
    </nav>
  </header>
</div>
<div class="wrapper row2">
  <div id="container" class="clear">
    <!-- content body -->
    <section id="shout">
      
      <h1>Welcome, <%= @theUser.firstname %>
      <img src="images/notification.png" alt="" style="width:20px; height:20px; float:right;">
      </h1>

    </section>
    <!-- main content -->
    <section id="services" class="clear">
      <!-- article 1 -->
      <article class="one_third">
        <nav>
          <ul>
            <li><a><%=link_to "Browse Shifts",listings_path %></a></li>
            <br>
            <li><a><%= link_to "Create A Shift", newlisting_path %></a></li>
            <br>
            <li><a><%= link_to "View Profile", profile_path %></a></li>
            <br>
            <% if @theUser.ismanager == true %>
              <li><%= link_to "Register New User", signup_path, class: "btn btn-primary" %></li>
            <% end %>
          </ul>
        </nav>

      </article>
      <div class="vl"></div>
      <!-- article 3 -->
      <article class="two_third lastbox">
      <table>
    <tr>
        <th>Day Of The Week</th>
        <th>Start Time</th>
        <th>End Time</th>
        <th>Shift Length</th>
        <th>Department</th>
        <th>Store</th>
          <th>Post A Shift</th>
    </tr>
    <% @shifts.each do |shift| %>
        <% if session[:user_id] == shift.userid %>
            <tr>
              <% case %>
              <% when shift.starttime < 24 %>
                  <td>Sunday</td>
                  <td><%= shift.starttime %>:00</td>
              <% when shift.starttime > 23 && shift.starttime < 48 %>
                  <td>Monday</td>
                  <td><%= shift.starttime - 24 %>:00</td>
              <% when shift.starttime > 47 && shift.starttime < 72 %>
                  <td>Tuesday</td>
                  <td><%= shift.starttime - 48 %>:00</td>
              <% when shift.starttime > 71 && shift.starttime < 96 %>
                  <td>Wednesday</td>
                  <td><%= shift.starttime - 72 %>:00</td>
              <% when shift.starttime > 95 && shift.starttime < 120 %>
                  <td>Thursday</td>
                  <td><%= shift.starttime - 96 %>:00</td>
              <% when shift.starttime > 119 && shift.starttime < 144 %>
                  <td>Friday</td>
                  <td><%= shift.starttime - 120 %>:00</td>
              <% when shift.starttime > 143 && shift.starttime < 168 %>
                  <td>Saturday</td>
                  <td><%= shift.starttime - 144 %>:00</td>
              <% end %>
              <% case %>
              <% when shift.endtime < 24 %>
                  <td><%= shift.endtime %>:00</td>
              <% when shift.endtime > 23 && shift.endtime < 48 %>
                  <td><%= shift.endtime - 24 %>:00</td>
              <% when shift.endtime > 47 && shift.endtime < 72 %>
                  <td><%= shift.endtime - 48 %>:00</td>
              <% when shift.endtime > 71 && shift.endtime < 96 %>
                  <td><%= shift.endtime - 72 %>:00</td>
              <% when shift.endtime > 95 && shift.endtime < 120 %>
                  <td><%= shift.endtime - 96 %>:00</td>
              <% when shift.endtime > 119 && shift.endtime < 144 %>
                  <td><%= shift.endtime - 120 %>:00</td>
              <% when shift.endtime > 143 && shift.endtime < 168 %>
                  <td><%= shift.endtime - 144 %>:00</td>
              <% end %>
                <td><%= shift.shiftlength %> hour(s)</td>
                <% if shift.department %>
                  <% if shift.department == 1 %>
                    <td>Cashier</td>
                  <% end%>
                  <% if shift.department == 2 %>
                    <td>Stock Handler</td>
                  <% end%>
                  <% if shift.department == 3 %>
                    <td>Dairy</td>
                  <% end%>
                  <% if shift.department == 4 %>
                    <td>Deli</td>
                  <% end%>
                  <% if shift.department == 5 %>
                    <td>Bakery</td>
                  <% end %>
                <% else %>
                  <td>No Department</td>
                <% end%>
                <% case %>
                <% when !shift.storeid %>
                  <td>Swanston St</td>
                <% when shift.storeid == 1 %>
                  <td>Swanston St</td>
                <% when shift.storeid == 2 %>
                  <td>Elizabeth St</td>
                <% when shift.storeid == 3 %>
                  <td>Bourke St</td>
                <% when shift.storeid == 4 %>
                  <td>Lygon St</td>
                <% when shift.storeid > 4 %>
                  <td>Queen's St</td>
                <% end %>
                  <td><%= link_to "Select", {:controller => "site_pages",
                                     :action => "movePublic",
                                     :id => shift.id,
                                     :userid => shift.userid}, method: "post",
                                  class: "btn btn-sm btn-success" %></td>
            </tr>
        <% end %>
    <% end %>
</table>
      </article>
    </section>
    <!-- ########################################################################################## -->
    <!-- ########################################################################################## -->
    <!-- ########################################################################################## -->
    <!-- ########################################################################################## -->
    <!-- / content body -->
  </div>
</div>
<!-- footer -->

</div>
</body>
</html>

app/views/site_pages/profile.html.erb
<!DOCTYPE html>
<html lang="en" dir="ltr">
<head>
<title>Profile</title>
<meta charset="UTF-8">
<link rel="stylesheet" href="css/layout.css" type="text/css">
<!--[if lt IE 9]><script src="scripts/html5shiv.js"></script><![endif]-->
</head>
<body>
<div class="wrapper row1">
  <header id="header" class="clear">
    <nav>
      <ul>
        <% if logged_in? %>
        <li class="last"><a><%= link_to "Log out", logout_path, method: :delete %></li>
        <% else %>
        <li><%= link_to "Log in", login_path %></li>
              <p>Not logged in</p>
        <% end %>
      </ul>
    </nav>
  </header>
</div>
<!-- content -->
<div class="wrapper row2">
  <div id="container" class="clear">
    <!-- content body -->
    <section id="shout">
      
      <h3><a><%= link_to "return to main page",   home_path %></a></h3>

    </section>
    <!-- main content -->
    <section id="services" class="clear">

      <!-- article 3 -->
      <h1>Profile </h1>
      <article class="three_third center">
<p>This will be the page for editing the user's profile</p>
<p>Logged In As: <%= @theUser.firstname %> <%= @theUser.lastname %></p>
<p>Email Address: <%= @theUser.emailaddress %></p>
<p>Phone Number: <%= @theUser.phonenumber %></p>
<% if @theUser.ismanager == true %>
  <p>Account status: Manager</p>
<% else %>
  <p>Account status: Employee</p>
<% end %>
<% if @theUser.storeid != nil%>
  <p>Store ID: <%= @theUser.storeid %></p>
<% end %>
          </article>
    </section>
    <!-- ########################################################################################## -->
    <!-- ########################################################################################## -->
    <!-- ########################################################################################## -->
    <!-- ########################################################################################## -->
    <!-- / content body -->
  </div>
</div>
<!-- footer -->

</body>
</html>

app/views/users/new.html.erb
<div class="row justify-content-md-center mt-5">
    <div class="col-4">
        <%= form_tag signup_path do |form| %>
        <div class="form-group">
            <% if @errors != nil %>
            <div class="alert alert-danger" role="alert">
                <% @errors.each do |error| %>
                <div><%= error %></div>
                <% end %>
            </div>
            <% end %>
        </div>
        <div class="form-group">
            <label><%= label_tag :firstname %></label>
            <%= text_field_tag :firstname, "", class: 'form-control' %>
            <small id="firstNameHelp" class="form-text text-muted">Enter your first name</small>
        </div>
        <div class="form-group">
            <label><%= label_tag :lastname %></label>
            <%= text_field_tag :lastname, "", class: 'form-control' %>
            <small id="lastNameHelp" class="form-text text-muted">Enter your full name</small>
        </div>
        <div class="form-group">
            <label><%= label_tag :password %></label>
            <%= password_field_tag :password, "", class: 'form-control' %>
            <small id="passwordHelp" class="form-text text-muted">Enter your password</small>
        </div>
        <div class="form-group">
            <label><%= label_tag :phonenumber %></label>
            <%= text_field_tag :phonenumber, "", class: 'form-control' %>
            <small id="phonenumberHelp" class="form-text text-muted">Enter your phonenumber</small>
        </div>
        <div class="form-group">
            <label><%= label_tag :storeid %></label>
            <%= text_field_tag :storeid, "", class: 'form-control' %>
            <small id="storeIDHelp" class="form-text text-muted">Enter your store's ID</small>
        </div>
        <div class="form-group">
            <label><%= label_tag :emailaddress %></label>
            <%= text_field_tag :emailaddress, "", class: 'form-control' %>
            <small id="emailHelp" class="form-text text-muted">Enter your email address</small>
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
        <% end %>
    </div>
</div>